a=input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(a)))
print('Só tem espaaço? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfabético? {}'.format(a.isalpha()))
print('É alfanumérico? {}'.format(a.isalnum()))
print('Está em maiúsculas? {}'.format(a.isupper()))
print('Está em minúsculas? {}'.format(a.islower()))
print('Está em capitalizada? {}'.format(a.istitle()))